# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8b8714457709a6a454bfc206b165fe191a78dc388d42a4bc6cbdc0ed801e89090b6d62565baf2218452ff9e4c3de77f0fd4090875970f1ff99685df1a624ff3

test:
  secret_key_base: 9ec78b537b5c20b3baedac26e327f526f4ee460316ff5718ba429d89abb88d8d68083a9e74aecbbc2a0a0b37b72ea3cc8cb5228f22b66fa145353f5cc595d28e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
